IRMS.POC.Joe/IRMS.POC/ApprovalWorkflowApp.Joe/ApprovalWorkflowApp/Controllers/AdminController.cs
using ApprovalWorkFlow.Business;
using ApprovalWorkFlow.BusinessDTOs;
using ApprovalWorkflowApp.UtilityClass;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace ApprovalWorkflowApp.Controllers
{
   // [Authorize(Roles = @"JNJ\JRD-APP-BCPASSAYMGMT-Approvers")]  //  [Authorize(Roles = @"JNJ\JRD-APP-BCPASSAYMGMT-DB")]
    //[Authorize(Roles = @"JNJ\JRD-APP-BCPASSAYMGMT-DB")]
    [AppAuthorizeAttribute(Roles = SystemRole.Administrators)]
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Audit(string itemsPerPage, string pageno)
        {
            //JavaScriptSerializer serializer = new JavaScriptSerializer();
            //List<AuditDTO> auditDTO = new List<AuditDTO>();
            //AdminBS adminBSobj = new AdminBS();

            //auditDTO = adminBSobj.GetAuditBS();

          //  ViewBag.AuditList = serializer.Serialize(auditDTO);

            return View();
        }

        [HttpGet]
        public ActionResult GetAuditList(string itemsPerPage, string pageno)
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            List<AuditDTO> auditDTO = new List<AuditDTO>();
            AdminBS adminBSobj = new AdminBS();

            auditDTO = adminBSobj.GetAuditBS(itemsPerPage, pageno);

            return Json(auditDTO, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ITSupport()
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            string logonUserName = string.Empty;
            string logonUserId = string.Empty;
            UserDetails userDetailsObj = new UserDetails();
            logonUserId = User.Identity.Name.ToString();
            userDetailsObj = LDAPinfoCollect.GetUserDetails(logonUserId);

            List<SupportApprovalDetailsDTO> myApprovalDetailsDTO = new List<SupportApprovalDetailsDTO>();
            AdminBS adminBSobj = new AdminBS();

            myApprovalDetailsDTO = adminBSobj.GetApprovalsBS(Convert.ToInt32(userDetailsObj.UserWWID), 0, "PendingApprovals");

            ViewBag.SupportApprovalList = serializer.Serialize(myApprovalDetailsDTO);

            return View("PendingSupportApprovals");
        }
    }
}

IRMS.POC.Joe/IRMS.POC/ApprovalWorkflowApp.Joe/ApprovalWorkflowApp/Controllers/ApprovalController.cs
using ApprovalWorkFlow.Business;
using ApprovalWorkFlow.BusinessDTOs;
using ApprovalWorkflowApp.Models;
using ApprovalWorkflowApp.UtilityClass;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace ApprovalWorkflowApp.Controllers
{
    public class ApprovalController : Controller
    {
        // GET: Approval
        public ActionResult PendingApprovals()
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            string logonUserName = string.Empty;
            string logonUserId = string.Empty;
            UserDetails userDetailsObj = new UserDetails();
            logonUserId = User.Identity.Name.ToString();
            userDetailsObj = LDAPinfoCollect.GetUserDetails(logonUserId);

            List<MyApprovalDetailsDTO> myApprovalDetailsDTO = new List<MyApprovalDetailsDTO>();
            GetApprovalBS getMyApprovalObj = new GetApprovalBS();

            myApprovalDetailsDTO = getMyApprovalObj.GetApprovalsBS(Convert.ToInt32(userDetailsObj.UserWWID), 0 ,"PendingApprovals");

            ViewBag.MyApprovalList = serializer.Serialize(myApprovalDetailsDTO);

            return View();
        }

        public ActionResult AllApprovals()
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            string logonUserId = string.Empty;
            UserDetails userDetailsObj = new UserDetails();
            logonUserId = User.Identity.Name.ToString();
            userDetailsObj = LDAPinfoCollect.GetUserDetails(logonUserId);

            List<MyApprovalDetailsDTO> myApprovalDetailsDTO = new List<MyApprovalDetailsDTO>();
            GetApprovalBS getMyApprovalObj = new GetApprovalBS();

            myApprovalDetailsDTO = getMyApprovalObj.GetApprovalsBS(Convert.ToInt32(userDetailsObj.UserWWID), 0, "All");

            ViewBag.MyApprovalList = serializer.Serialize(myApprovalDetailsDTO);

            return View();
        }

        public ActionResult GetRequest(int id)
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            string logonUserId = string.Empty;
            UserDetails userDetailsObj = new UserDetails();
            logonUserId = User.Identity.Name.ToString();
            userDetailsObj = LDAPinfoCollect.GetUserDetails(logonUserId);

            List<MyApprovalDetailsDTO> myApprovalDetailsDTO = new List<MyApprovalDetailsDTO>();
            GetApprovalBS getMyApprovalObj = new GetApprovalBS();
          
            myApprovalDetailsDTO = getMyApprovalObj.GetApprovalsBS(Convert.ToInt32(userDetailsObj.UserWWID), id, "PendingApprovals");

            ViewBag.MyApprovalList = serializer.Serialize(myApprovalDetailsDTO);

            return View("PendingApprovals");
        }
        [HttpPost]
        public ActionResult UpdateRequest(ApprovalRequestDetailsVM approvalRequestDetailsVM)
        {
            string eightDigitNumber = string.Empty;
            GetApprovalBS getApprovalBSobj = new GetApprovalBS();

            UpdateRequestDetailsDTO UpdateRequestDetailsDTO = new UpdateRequestDetailsDTO {
                 Comment= approvalRequestDetailsVM.Comment,
                 Option= approvalRequestDetailsVM.Option,
                 RequestNo= approvalRequestDetailsVM.RequestNo,
                 UserName= approvalRequestDetailsVM.UserName
            };

            if (approvalRequestDetailsVM.Option=="Approve")
            {
                Random r = new Random();
                int randNum = r.Next(1000000);
                eightDigitNumber = randNum.ToString("D8");
                UpdateRequestDetailsDTO.TaskId = "TASK0000" + eightDigitNumber;
            }
            else
            {
                UpdateRequestDetailsDTO.TaskId = eightDigitNumber;
            }

            string status = getApprovalBSobj.UpdateRequest(UpdateRequestDetailsDTO);
            ApprovalStatus approvalStatusVM = new ApprovalStatus();
            if (status.ToUpper() == "UPDATED")
            {
                approvalStatusVM.Status = "UPDATED";
                approvalStatusVM.TaskId = "TASK0000" + eightDigitNumber;
            }
            else
            {
                approvalStatusVM.Status = "FAILED";
                approvalStatusVM.TaskId = eightDigitNumber;
            }

            
            return Json(approvalStatusVM, JsonRequestBehavior.AllowGet);
            
        }
    }
}

IRMS.POC.Joe/IRMS.POC/ApprovalWorkflowApp.Joe/ApprovalWorkflowApp/Controllers/SubmitRequestController.cs
using ApprovalWorkflowApp.UtilityClass;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Script.Serialization;
using System.Web.Mvc;
using System.DirectoryServices.AccountManagement;
using ApprovalWorkflowApp.Models;
using System.Net.Mail;
using ApprovalWorkFlow.Business;
using ApprovalWorkFlow.BusinessDTOs;
using System.IO;
using System.Web.UI;
using System.Text;

namespace ApprovalWorkflowApp.Controllers
{
    public class SubmitRequestController : Controller
    {
        // GET: SubmitRequest
        public ActionResult IDSSubmitRequest()
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            string logonUserName = string.Empty;
            string logonUserId = string.Empty;
            UserDetails userDetailsObj = new UserDetails();

            logonUserId = User.Identity.Name.ToString();
            userDetailsObj = LDAPinfoCollect.GetUserDetails(logonUserId);
            userDetailsObj.ApplicationId = "1";

            ViewBag.UserDetails = serializer.Serialize(userDetailsObj);
            return View();
        }
        [HttpPost]
        public ActionResult ValidateElectronicSign(UserModel userVM)
        {
            bool IsValidUser = false;
            using (PrincipalContext context = new PrincipalContext(ContextType.Domain))
            {
                IsValidUser = context.ValidateCredentials(userVM.UserName, userVM.Password);
            }

            return Json(IsValidUser, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SubmitRequest(RequestDetailsVM requestDetailsVM)
        {
            bool IsRequestSubmitted = true;

            RequestBS requestBSObj = new RequestBS();
            RequestParamsDTO requestDTO = new RequestParamsDTO {
                IDSSPEntity = requestDetailsVM.IDSSPEntity,
                SASDDEntity = requestDetailsVM.SASDDEntity,
                HPALMEntity = requestDetailsVM.HPALMEntity,
                MKSIntegrity = requestDetailsVM.MKSIntegrity,
                DMCCEntity = requestDetailsVM.DMCCEntity,
                IDSDropZoneEntity = requestDetailsVM.IDSDropZoneEntity,
            };

            UserDTO requesterUserDTO = new UserDTO {
                 EmailId = requestDetailsVM.UserEmailId,
                 FirstName = requestDetailsVM.FirstName,
                 LastName =requestDetailsVM.LastName,
                 NTId = requestDetailsVM.NTId,
                 UserId = requestDetailsVM.UserId
            };
            RequesterDTO requesterDTO = new RequesterDTO { User = requesterUserDTO };
           
            UserDTO managerUserDTO = new UserDTO
            {
                EmailId = requestDetailsVM.ManagerEmailId,
                FirstName = requestDetailsVM.ManagerFirstName,
                LastName = requestDetailsVM.ManagerLastName,
                NTId = requestDetailsVM.ManagerNetworkId,
                UserId = requestDetailsVM.ManagerWWID
            };
            ManagerDTO managerDTO = new ManagerDTO { User = managerUserDTO };
            RequestUserDetailsDTO requestUserDetailsDTO = new RequestUserDetailsDTO {
                ApplicationId = requestDetailsVM.ApplicationId,
                ManagerDTO = managerDTO,
                RequesterDTO = requesterDTO,
                RequestCreatedDt = DateTime.Now.ToString(),
                RequestParams= requestDTO,
                RequestStateId = requestDetailsVM.RequestStateId,
                StatusInd="1"
            };

            int requestId = requestBSObj.SubmitRequestBS(requestUserDetailsDTO);
            if (requestId != 0)
            {
                try
                {
                    MailMessage mail = new MailMessage();
                    mail.From = new MailAddress(requestDetailsVM.UserEmailId);   
                    mail.To.Add(requestDetailsVM.ManagerEmailId);
                    SmtpClient client = new SmtpClient();
                    client.Port = 25;
                    client.DeliveryMethod = SmtpDeliveryMethod.Network;
                    client.Credentials = new System.Net.NetworkCredential(requestDetailsVM.NTId, requestDetailsVM.Password);
                    client.Host = "smtp.na.jnj.com";
                    mail.Subject = "Request Id:"+requestId+"-Approval Request For" + requestDetailsVM.UserName;
                    mail.IsBodyHtml = true;

                  //  StringWriter writer = new StringWriter();
                  //  HtmlTextWriter html = new HtmlTextWriter(writer);

                  //  //html.RenderBeginTag(HtmlTextWriterTag.H1);
                  //  //html.WriteEncodedText("Heading Here");
                  //  //html.RenderEndTag();
                  //  html.WriteEncodedText(String.Format("Dear {0} {1}", requestDetailsVM.ManagerName,','));
                  //  html.WriteBreak();
                  //  html.RenderBeginTag(HtmlTextWriterTag.P);
                  //  html.WriteEncodedText("Please visit below link to make the approval");
                  //  html.RenderEndTag();
                  ////  html.WriteBreak();
                  //  html.AddAttribute(HtmlTextWriterAttribute.Href, "http://WIN-HRCH1I5K9R1.wks.jnj.com/Approval/GetRequest/" + requestId);
                  //  html.RenderBeginTag(HtmlTextWriterTag.A);
                  //  html.WriteEncodedText("Approval Link");
                  //  html.RenderEndTag();
                  ////  html.WriteBreak();
                  //  html.RenderBeginTag(HtmlTextWriterTag.P);
                  //  html.WriteEncodedText("Thanks and Regards,");
                  ////  html.RenderEndTag();
                  //  html.WriteBreak();
                  ////  html.RenderBeginTag(HtmlTextWriterTag.P);
                  //  html.WriteEncodedText("IDS Support Team");
                  //  html.RenderEndTag();
                  // // html.WriteBreak();
                  //  html.Flush();

                  //  string htmlString = writer.ToString();

                    ViewData.Add("RequestId", requestId);
                    ViewData.Add(new KeyValuePair<string, object>("Approver", requestDetailsVM.ManagerName));
                    ViewData.Add(new KeyValuePair<string, object>("Requester", requestDetailsVM.UserName));

                    string htmlEmailBody = HTMLHelper.ToHtml("ApprovalEmailTemplate", ViewData, this.ControllerContext).ToString();
                    mail.Body = htmlEmailBody.ToString();

                    client.Send(mail);
                }
                catch (Exception ex)
                {
                    IsRequestSubmitted = false;
                    return Json(IsRequestSubmitted, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(IsRequestSubmitted, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file, string user)
        {
            FileUploadViewModel fileUploadVM = new FileUploadViewModel();
            if (file != null && file.ContentLength > 0)
                try
                {
                    
                    string path = Path.Combine(Server.MapPath("~/Images"),
                                               Path.GetFileNameWithoutExtension(file.FileName)+ "_"+ user+ "_" + DateTime.Now.ToString("yyyyMMddHHmmssfff") +Path.GetExtension(file.FileName));
                    DirectoryInfo dir = new DirectoryInfo(HttpContext.Server.MapPath("~/Images/"));
                    if (!dir.Exists)
                    {
                        dir.Create();
                    }
                    file.SaveAs(path);
                    fileUploadVM = new FileUploadViewModel()
                    {
                        Message = "File uploaded successfully",
                        FilePath = path
                    };
                }
                catch (Exception ex)
                {
                    fileUploadVM = new FileUploadViewModel()
                    {
                        Message = "ERROR:" + ex.Message.ToString(),
                        FilePath = null
                    };
                }
            else
            {
                fileUploadVM = new FileUploadViewModel()
                {
                    Message = "You have not specified a file.",
                    FilePath = null
                };
            }
            return Json(fileUploadVM, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SearchManager(string managerNTId)
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            UserDetails userDetailsObj = new UserDetails();

            userDetailsObj = LDAPinfoCollect.GetUserDetails(managerNTId);

            return Json(userDetailsObj, JsonRequestBehavior.AllowGet);
        }
    }
}

IRMS.POC.Joe/IRMS.POC/ApprovalWorkflowApp.Joe/ApprovalWorkflowApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button"  id="btnNavMenu" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(" ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", @style = "background-image:url('/AppImages/Hermes.jpeg'); display:block; height: 46px; width: 113px" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Request Forms <b class="caret"></b></a>
                        <ul class="dropdown-menu multi-level">
                            @*<li>@Html.ActionLink("Empower Request Form", "EmpowerSubmitRequest", "SubmitRequest")</li>
                            <li>@Html.ActionLink("CyberLab Request Form", "EmpowerSubmitRequest", "SubmitRequest")</li>
                            <li>@Html.ActionLink("BCP Assay Request Form", "EmpowerSubmitRequest", "SubmitRequest")</li>*@
                            <li>@Html.ActionLink("Hermes IDS Application Access Request Form", "IDSSubmitRequest", "SubmitRequest")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Approval List<b class="caret"></b></a>
                        <ul class="dropdown-menu multi-level">
                            <li>@Html.ActionLink("Pending Approvals", "PendingApprovals", "Approval")</li>
                            <li>@Html.ActionLink("All Requests", "AllApprovals", "Approval")</li>
                        </ul>
                    </li>
                    @if (HttpContext.Current.User.IsInRole("JRD-APP-BCPASSAYMGMT-DB") || HttpContext.Current.User.Identity.Name.ToUpper() == "NA\\SSAHA14")
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
                                <ul class="dropdown-menu multi-level">
                                    <li>@Html.ActionLink("Audit", "Audit", "Admin")</li>
                                    <li>@Html.ActionLink("For IT Support", "ITSupport", "Admin")</li>
                                </ul>
                            </li>
                        }

                </ul>
                <p class="nav navbar-text navbar-right">Welcome, @HttpContext.Current.Session["CurrentUser"].ToString()!</p> @*@User.Identity.Name*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Johnson & Johnson Inc.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/AngularScripts")


    <script src="~/Scripts/angular-toastr.tpls.js"></script>
    @*<script src="~/Scripts/dirPagination.js"></script>*@

    <link href="~/Content/isteven-multi-select.css" rel="stylesheet" />
    <script src="~/Scripts/isteven-multi-select.js"></script>
    <script src="~/Scripts/angular-ui/ui-bootstrap-tpls.js"></script>
    <link href="~/Content/ui-bootstrap-csp.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.rawgit.com/esvit/ng-table/1.0.0/dist/ng-table.min.css">
    <script src="https://cdn.rawgit.com/esvit/ng-table/1.0.0/dist/ng-table.js"></script>

    <link rel="stylesheet" href="http://mbenford.github.io/ngTagsInput/css/ng-tags-input.min.css" />
    <script src="http://mbenford.github.io/ngTagsInput/js/ng-tags-input.min.js"></script>
    <script src="~/Scripts/ng-file-upload.min.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>